name-template: 'release-v$NEXT_PATCH_VERSION'
tag-template: 'release-v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feat'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Performance'
    labels:
      - 'chore'
      - 'perf'
      - 'style'
      - 'refactor'
      - 'revert'
      - 'wip'
  - title: 'Ci'
    labels:
      - 'ci'
      - 'build'
      - 'init'
  - title: 'Docs'
    labels:
      - 'docs'
      - 'build'
      - 'init'
      - 'workflow'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  # What's Changed
  $CHANGES
