name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  draft_release:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.11.0
        name: Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
